version: '3.7'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: pet-lover
      POSTGRES_PASSWORD: pet-lover
      POSTGRES_DB: pet-lover
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080